kind: Service
apiVersion: v1
metadata:
  labels:
    app: pingw10
  name:  pingw10-svc
  namespace: group-1-prod
spec:
  selector:
    app:  pingw10
  type:  ClusterIP
  ports:
  - name:  map-to-app
    port: 80
    protocol: TCP
    targetPort: 3000