apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pingw91010
  name: pingw91010
  namespace: group-1-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingw91010
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pingw91010
    spec:
      containers:
        #- image: pingkunga/w91010
        - image: pingkunga/w91010:67d89d
          imagePullPolicy: Always
          name: w91010
          resources: {}
          envFrom:
            - configMapRef:
                name: pingconfig
            - secretRef:
                name: pingsecret
status: {}
